port: ":8082"
env: staging
app_code: backend_testing_t
db: 
  host: localhost
  username: postgres
  password: password
  name: backend_test_mid_test
  port: 5432
jwt_encryption_key: 9c1d50f1bda04eaf919b15428e6b8676